### ISSUE TITLE
Bitmap support?

### ISSUE THREAD

**Issue by ZeoWorks** [Einarin/DwmWindowClone#1]
Hi,
Any way to convert this data to a bitmap or something readable texture-wise?
Thanks!

**Comment by Einarin** [comment]
Sorry I missed this, unfortunately there isn't a way to read the data using this method. This app uses the DWM thumbnail API, and the way that API works is that we're sending requests to DWM.exe (the desktop compositor) to draw another copy of a given window. Since DWM.exe is actually doing the drawing there is no way for us to access the data.

However, if you're able to require Windows 8 or newer Microsoft introduced the [DXGI Desktop Duplication API](https://learn.microsoft.com/en-us/windows/win32/direct3ddxgi/desktop-dup-api) which does provide readable textures, although the texture data is of the display rather than per window.
